# -*- coding: utf-8 -*-
"""Data-Scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16N74SnKc_jPypUJ3qa-wh92kqDHak304
"""

## Import Modules
from bs4 import BeautifulSoup
import requests
import pandas as pd

# Request page sourse from URL

url = "https://en.wikipedia.org/wiki/List_of_unicorn_startup_companies"

page = requests.get(url)
page

## display page sourse code
page.content

## beautify table content
soup = BeautifulSoup(page.content, "html.parser")
print(soup.prettify)

## get exact table
table = soup.find_all('table', class_ = 'wikitable sortable sticky-header')
print(table)

## get exact table
table = soup.find_all('table')[2]
print(table)

## extract column header
world_titles = table.find_all('th')
print(world_titles)

world_table_titles = [title.text.strip() for title in world_titles]
print(world_table_titles)

## Create table columns
df = pd.DataFrame(columns = world_table_titles)
df

## extract data
column_data = table.find_all('tr')
column_data

for row in column_data[1:]:
  row_data = row.find_all('td')
  individual_row_data = [data.text.strip() for data in row_data]

  length = len(df)
  df.loc[length] = individual_row_data

df

##df.to_csv("Unicorn Startups.csv", index=False)
from google.colab import files
files.download("Unicorn Startups.csv")



df = pd.read_csv('Unicorn Startups.csv', encoding='latin1')

df['Month_Year'] = df['Valuation date'].str.replace(r'[^\w\s]', '', regex=True)  # remove special chars
df['Month_Year'] = df['Month_Year'].str.extract(r'([A-Za-z]+)\s+(\d{4})').agg(' '.join, axis=1)